name: Maven TestNG project Gitactions browserstack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0
      with:
            chrome-version: '114'
	  
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v2.2.1
      with:
             chromedriver-version: '114.0.5735.90'
   
    - name: check version
      run: google-chrome --version 
   
   
   # - name: Run with Maven
   #   run: mvn test


