name: Maven TestNG project Gitactions browserstack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

   
   
    - name: check version
      run: google-chrome --version 

    - name: Chrome/Chromedriver Matcher Action
      uses: jamesmortensen/chromedriver-matcher-action@v1.0.1
          
   
   
   # - name: Run with Maven
   #   run: mvn test


